FROM --platform=linux/386 debian:bookworm as builder

ENV DEBIAN_FRONTEND=noninteractive

# Install GCC and build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    make \
    libc6-dev \
    wget libssl-dev curl gcc-multilib libc6-dev g++-multilib gcc-12-multilib build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY src/ .
CMD ["bash"]
RUN gcc -m32 -print-libgcc-file-name
WORKDIR /build
COPY ./src/ .
RUN make potato32
#RUN mkdir rootfs && curl -L 'https://dl-cdn.alpinelinux.org/alpine/v3.21/releases/x86_64/alpine-minirootfs-3.21.3-x86_64.tar.gz' | tar -xz -C rootfs

FROM --platform=linux/386 debian:bookworm-slim
RUN apt-get update -y && apt-get install -y libssl3 libc6 curl
RUN groupadd -g 22222 potato
WORKDIR /app
COPY --from=builder /build/potato32 .
#COPY --from=builder rootfs .
COPY --chmod=0640 userlist .
COPY res /app/res
RUN curl -o /app/toybox "https://landley.net/bin/toybox/latest/toybox-i686" && chmod +x /app/toybox

EXPOSE 222
ENTRYPOINT ["./potato32"]
