
name: Build and Test API

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: ./build.sh

      - name: Run container
        run: |
          ./run64.sh 

      - name: Test API with wget
        run: |
          wget -qO- http://localhost:80/login
          wget -qO- http://localhost:80/run

      - name: Show container logs
        if: always()
        run: docker logs potato
